import React, { useState, useEffect } from "react";
import ScreenHeading from "../../utilities/ScreenHeading/ScreenHeading";
import ScrollService from "../../utilities/ScrollService";
import Animations from "../../utilities/Animations";
import "./Resume.css";

const Resume = (props) => {
  /* STATES */
  const [selectedBulletIndex, setSelectedBulletIndex] = useState(0);
  const [carousalOffsetStyle, setCarousalOffsetStyle] = useState({});

  let fadeInScreenHandler = (screen) => {
    if (screen.fadeInScreen !== props.id) return;

    Animations.animations.fadeInScreen(props.id);
  };
  const fadeInSubscription =
    ScrollService.currentScreenFadeIn.subscribe(fadeInScreenHandler);

  /* REUSABLE MINOR COMPONENTS */
  const ResumeHeading = (props) => {
    return (
      <div className="resume-heading">
        <div className="resume-main-heading">
          <div className="heading-bullet"></div>
          <span>{props.heading ? props.heading : ""}</span>
          {props.fromDate && props.toDate ? (
            <div className="heading-date">
              {props.fromDate + "-" + props.toDate}
            </div>
          ) : (
            <div></div>
          )}
        </div>
        <div className="resume-sub-heading">
          <span>{props.subHeading ? props.subHeading : ""}</span>
        </div>
        <div className="resume-heading-description">
          <span>{props.description ? props.description : ""}</span>
        </div>
      </div>
    );
  };

  /* STATIC RESUME DATA FOR THE LABELS*/
  const resumeBullets = [
    { label: "Education", logoSrc: "education.svg" },
    { label: "Programming Skills", logoSrc: "programming-skills.svg" },
    { label: "Projects", logoSrc: "projects.svg" },
    { label: "Interests", logoSrc: "interests.svg" },
    { label: "Achievements", logoSrc: "work-history.svg" },
  ];

  //here we have

  const programmingSkillsDetails = [
    { skill: "Data structure and Algo" },
    { skill: "JavaScript" },
    { skill: "React JS" },
    { skill: "Node JS" },
    { skill: "Express JS" },
    { skill: "Mongo DB" },
    { skill: "Postman" },
    { skill: "HTML" },
    { skill: "CSS" },
    { skill: "Material ui" },
  ];

  const projectsDetails = [
    {
      title: "Haleema-Fashions Website",
      duration: { fromDate: "2022", toDate: "2022" },
      description:
        "Individual built website to demonstrates a basic flow of an ecommerce page.",
      subHeading: "Technologies Used: MERN| Redux| Material Ui",
    },
    {
      title: "Desert Cart website",
      duration: { fromDate: "2021", toDate: "2022" },
      description:
        "Project-Desert Cart ,This is an Indian e-commerce Website and we made this clone in just 4 Days",
      subHeading: "Technologies Used:   Html | css | Javascript",
    },
    {
      title: "Shoppers Stop  website ",
      duration: { fromDate: "2021", toDate: "2022" },
      description:
        "Project-This website is an Indian shopping Website and we made this clone in just 4 Days",
      subHeading: "Technologies Used:   Html| css| Javascript| Mongodb |Node js|expressjs",
    },
  ];

  const resumeDetails = [
    <div className="resume-screen-container" key="education">
      <ResumeHeading
        heading={" MASAI - THE CODING SCHOOL"}
        subHeading={
          "Completed MERN stack developement course along with Data structure and algorithms"
        }
        fromDate={"2021"}
        toDate={"2022"}
      />

      <ResumeHeading
        heading={"HMS INSTITUTE OF TECHNOLOGY(Tumkur)"}
        subHeading={"B.E in Computer Science Engineering(Distinction)"}
        fromDate={"2017"}
        toDate={"2021"}
      />
      <div className="clg-project">
        <p className="stacker">PROJECT: Toxic comment</p>
        <span className="stacker-details">
          Details: The problem undertaken in this project is
        </span>
        <p className="three-d">
          to find out the toxic data comments in the social
          media data generated by the users
        </p>
        <p className="iit-delhi">.</p>
      </div>

      <div className="marwari-clg">
        <ResumeHeading
          heading={" 10+2(Bangalore)"}
          subHeading={"St.Charles women pu college"}
          fromDate={"2015"}
          toDate={"2017"}
        />
      </div>
    </div>,

    /* PROGRAMMING SKILLS */
    <div
      className="resume-screen-container programming-skills-container"
      key="programming-skills"
    >
      {programmingSkillsDetails.map((skill, index) => (
        <div className="skill-parent" key={index}>
          <div className="heading-bullet bullet-down"></div>
          <span>{skill.skill}</span>
          <div className="skill-percentage">
            <div
              style={{ width: skill.ratingPercentage + "%" }}
              className="active-percentage-bar"
            ></div>
          </div>
        </div>
      ))}
    </div>,

    /* PROJECTS */
    <div className="resume-screen-container" key="projects">
      {projectsDetails.map((projectsDetails, index) => (
        <ResumeHeading
          key={index}
          heading={projectsDetails.title}
          subHeading={projectsDetails.subHeading}
          description={projectsDetails.description}
          fromDate={projectsDetails.duration.fromDate}
          toDate={projectsDetails.duration.toDate}
        />
      ))}
    </div>,

    /* Interests */
    <div className="resume-screen-container" key="interests">
      <ResumeHeading
        heading="Coding:"
        description="I love to design a website for greate user experience , taking care of every single little things so that a user can have good experience and I always try to learn new technologies so that I could match the current demanding skills in the industries. "
      />
      <ResumeHeading
        heading="Teaching:"
        description="Apart from being a tech enthusiast and a code writer, I also love to teach people what I know simply because I believe in sharing."
      />
      <ResumeHeading
        heading="Sports:"
        description="I was into sports from my school days ,that is from 4th grade. And I still maintain the skill of playing badminton."
      />
    </div>,

    <div className="resume-screen-container" key="Achievements">
      <div className="experience-container">
        <div className="cs-it">
          <ResumeHeading
            heading={"Apart from CS-IT"}
            subHeading={"ACCOMPLISHMENTS:"}
            // fromDate={"2021"}
            // toDate={"Present"}
          />
        </div>
        <div className="experience-description">
          <span className="resume-description-text"></span>
        </div>
        <div className="experience-description">
          <span className="resume-description-text">
            -I have been the Vice-President ,while I was pursuing my 10+2 .{" "}
            <br />
            - I was the class representative for 4 years,throughout my
            Engineering
            <br />
            - Represented district level Tournament in Badminton <br />
            - Contributed for needy people during pandemic through (Pledge Smile Foundation)badminton.
          </span>
          <br />
        </div>
        {/* <br /> */}

        <div className="my-stuff">
          <ResumeHeading
            heading={"My Stuffs"}
            subHeading={"INTERESTS AND HOBBIES:"}
          />
        </div>
        <br />
        <div className="intrest">
          <span className="resume-description-text-my">
            -  I love to help people,donate for Orphange. <br />
            And one of my hobbie is to read books <br />- Surfing tech things and try to learn new stuff.
          </span>
        </div>
      </div>
    </div>,
  ];

  const handleCarousal = (index) => {
    let offsetHeight = 360;

    let newCarousalOffset = {
      style: { transform: "translateY(" + index * offsetHeight * -1 + "px)" },
    };

    setCarousalOffsetStyle(newCarousalOffset);
    setSelectedBulletIndex(index);
  };

  const getBullets = () => {
    return resumeBullets.map((bullet, index) => (
      <div
        onClick={() => handleCarousal(index)}
        className={
          index === selectedBulletIndex ? "bullet selected-bullet" : "bullet"
        }
        key={index}
      >
        <img
          className="bullet-logo"
          src={require(`../../assets/Resume/${bullet.logoSrc}`).default}
          alt="B"
        />
        <span className="bullet-label">{bullet.label}</span>
      </div>
    ));
  };

  const getResumeScreens = () => {
    return (
      <div
        style={carousalOffsetStyle.style}
        className="resume-details-carousal"
      >
        {resumeDetails.map((ResumeDetail) => ResumeDetail)}
      </div>
    );
  };

  useEffect(() => {
    return () => {
      /* UNSUBSCRIBE THE SUBSCRIPTIONS */
      fadeInSubscription.unsubscribe();
    };
  }, [fadeInSubscription]);

  return (
    <div
      className="resume-container screen-container fade-in"
      id={props.id || ""}
    >
      <div className="resume-content">
        <ScreenHeading title={"Resume"} subHeading={"My formal Bio Details"} />
        <div className="resume-card">
          <div className="resume-bullets">
            <div className="bullet-container">
              <div className="bullet-icons"></div>
              <div className="bullets">{getBullets()}</div>
            </div>
          </div>

          <div className="resume-bullet-details">{getResumeScreens()}</div>
        </div>
      </div>
    </div>
  );
};

export default Resume;
